// Code generated by protoc-gen-go. DO NOT EDIT.
// source: HttpPlugin.proto

package plugin

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Trigger struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Endpoint             string            `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Ext                  map[string]string `protobuf:"bytes,3,rep,name=ext,proto3" json:"ext,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Trigger) Reset()         { *m = Trigger{} }
func (m *Trigger) String() string { return proto.CompactTextString(m) }
func (*Trigger) ProtoMessage()    {}
func (*Trigger) Descriptor() ([]byte, []int) {
	return fileDescriptor_87426c90ca738317, []int{0}
}

func (m *Trigger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trigger.Unmarshal(m, b)
}
func (m *Trigger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trigger.Marshal(b, m, deterministic)
}
func (m *Trigger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trigger.Merge(m, src)
}
func (m *Trigger) XXX_Size() int {
	return xxx_messageInfo_Trigger.Size(m)
}
func (m *Trigger) XXX_DiscardUnknown() {
	xxx_messageInfo_Trigger.DiscardUnknown(m)
}

var xxx_messageInfo_Trigger proto.InternalMessageInfo

func (m *Trigger) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Trigger) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *Trigger) GetExt() map[string]string {
	if m != nil {
		return m.Ext
	}
	return nil
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_87426c90ca738317, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Trigger)(nil), "plugin.Trigger")
	proto.RegisterMapType((map[string]string)(nil), "plugin.Trigger.ExtEntry")
	proto.RegisterType((*Response)(nil), "plugin.Response")
}

func init() { proto.RegisterFile("HttpPlugin.proto", fileDescriptor_87426c90ca738317) }

var fileDescriptor_87426c90ca738317 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xdd, 0x0d, 0x6e, 0xe3, 0x08, 0xba, 0x0c, 0x1e, 0xc2, 0x9e, 0xca, 0x9e, 0x8a, 0x60,
	0x0e, 0x15, 0x44, 0xea, 0xb9, 0xa0, 0x37, 0x09, 0xfe, 0x01, 0xed, 0x0e, 0x4b, 0x68, 0x49, 0x42,
	0x92, 0x2d, 0xed, 0x4f, 0xf1, 0xdf, 0xca, 0x66, 0x37, 0x0a, 0xde, 0xf2, 0x3d, 0xf2, 0xde, 0x9b,
	0x19, 0xa8, 0x5f, 0x63, 0x74, 0xef, 0x87, 0xa1, 0xd7, 0x46, 0x3a, 0x6f, 0xa3, 0xc5, 0xca, 0x25,
	0x6a, 0xbf, 0x0b, 0x58, 0x7c, 0x78, 0xdd, 0xf7, 0xe4, 0xf1, 0x06, 0x4a, 0xdd, 0x89, 0x62, 0x59,
	0xac, 0xae, 0x54, 0xa9, 0x3b, 0x6c, 0x80, 0x93, 0xe9, 0x9c, 0xd5, 0x26, 0x8a, 0x32, 0xa9, 0xbf,
	0x8c, 0xf7, 0xc0, 0xe8, 0x14, 0x05, 0x5b, 0xb2, 0xd5, 0xf5, 0x5a, 0xc8, 0x29, 0x4d, 0xce, 0x49,
	0x72, 0x7b, 0x8a, 0x5b, 0x13, 0xfd, 0x59, 0x8d, 0x9f, 0x9a, 0x27, 0xe0, 0x59, 0xc0, 0x1a, 0xd8,
	0x9e, 0xce, 0x73, 0xc9, 0xf8, 0xc4, 0x3b, 0xb8, 0x3c, 0x7e, 0x1e, 0x06, 0x9a, 0x2b, 0x26, 0xd8,
	0x94, 0xcf, 0x45, 0xbb, 0x01, 0xae, 0x28, 0x38, 0x6b, 0x02, 0xa1, 0x80, 0x45, 0x18, 0x76, 0x3b,
	0x0a, 0x21, 0x79, 0xb9, 0xca, 0x38, 0xfa, 0xc9, 0x7b, 0xeb, 0xb3, 0x3f, 0xc1, 0xfa, 0x05, 0xe0,
	0x6f, 0x67, 0x7c, 0x80, 0xea, 0xcd, 0x1c, 0xed, 0x9e, 0xf0, 0xf6, 0xdf, 0xa8, 0x4d, 0x9d, 0x85,
	0x5c, 0xd5, 0x5e, 0x7c, 0x55, 0xe9, 0x46, 0x8f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x5f,
	0xcb, 0xd8, 0x37, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HttpPluginClient is the client API for HttpPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HttpPluginClient interface {
	Invoke(ctx context.Context, in *Trigger, opts ...grpc.CallOption) (*Response, error)
}

type httpPluginClient struct {
	cc *grpc.ClientConn
}

func NewHttpPluginClient(cc *grpc.ClientConn) HttpPluginClient {
	return &httpPluginClient{cc}
}

func (c *httpPluginClient) Invoke(ctx context.Context, in *Trigger, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/plugin.HttpPlugin/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HttpPluginServer is the server API for HttpPlugin service.
type HttpPluginServer interface {
	Invoke(context.Context, *Trigger) (*Response, error)
}

func RegisterHttpPluginServer(s *grpc.Server, srv HttpPluginServer) {
	s.RegisterService(&_HttpPlugin_serviceDesc, srv)
}

func _HttpPlugin_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Trigger)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpPluginServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.HttpPlugin/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpPluginServer).Invoke(ctx, req.(*Trigger))
	}
	return interceptor(ctx, in, info, handler)
}

var _HttpPlugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.HttpPlugin",
	HandlerType: (*HttpPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _HttpPlugin_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "HttpPlugin.proto",
}
